from __future__ import unicode_literals

__all__ = ('Key', )

class Key:
    Escape = '<Escape>'

    ControlA = '<C-A>'
    ControlB = '<C-B>'
    ControlC = '<C-C>'
    ControlD = '<C-D>'
    ControlE = '<C-E>'
    ControlF = '<C-F>'
    ControlG = '<C-G>'
    ControlH = '<C-H>'
    ControlI = '<C-I>'
    ControlJ = '<C-J>'
    ControlK = '<C-K>'
    ControlL = '<C-L>'
    ControlM = '<C-M>'
    ControlN = '<C-N>'
    ControlO = '<C-O>'
    ControlP = '<C-P>'
    ControlQ = '<C-Q>'
    ControlR = '<C-R>'
    ControlS = '<C-S>'
    ControlT = '<C-T>'
    ControlU = '<C-U>'
    ControlV = '<C-V>'
    ControlW = '<C-W>'
    ControlX = '<C-X>'
    ControlY = '<C-Y>'
    ControlZ = '<C-Z>'

    ControlSpace = '<C-Space>'
    ControlBackslash = '<C-Backslash>'
    ControlSquareClose = '<C-SquareClose>'
    ControlCircumflex = '<C-Circumflex>'
    ControlUnderscore = '<C-Underscore>'

    Backspace   = '<BS>'
    Up          = '<Up>'
    Down        = '<Down>'
    Right       = '<Right>'
    Left        = '<Left>'
    Home        = '<Home>'
    End         = '<End>'
    Delete      = '<Delete>'
    ShiftDelete = '<ShiftDelete>'
    PageUp      = '<PageUp>'
    PageDown    = '<PageDown>'
    Tab         = ControlI
    BackTab     = '<BackTab>' # shift + tab

    F1 = '<F1>'
    F2 = '<F2>'
    F3 = '<F3>'
    F4 = '<F4>'
    F5 = '<F5>'
    F6 = '<F6>'
    F7 = '<F7>'
    F8 = '<F8>'
    F9 = '<F9>'
    F10 = '<F10>'
    F11 = '<F11>'
    F12 = '<F12>'
    F13 = '<F13>'
    F14 = '<F14>'
    F15 = '<F15>'
    F16 = '<F16>'
    F17 = '<F17>'
    F18 = '<F18>'
    F19 = '<F19>'
    F20 = '<F20>'

    # Matches any key.
    Any = '<Any>'
